#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.wireguard"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.wireguard" "${2}"
        fi

        # load system settings
        sysctl -p /etc/sysctl.d/ip_forward.conf
        # load wireguard module
        modprobe wireguard
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
